name: turkradyo
description: "A modern Flutter radio streaming application with dark theme."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Audio
  just_audio: ^0.9.36
  audio_service: ^0.18.12

  # UI & Styling
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.10
  lottie: ^3.1.0

  # Utilities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # HTTP
  http: ^1.1.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/

# Splash Screen Configuration
flutter_native_splash:
  color: "#8B5CF6"  # Header Purple
  image: assets/images/splash_logo.png
  color_dark: "#7C3AED"  # Card Purple Dark
  image_dark: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#8B5CF6"
  web: false
